package com.example.tavanyab.db;

import org.greenrobot.greendao.annotation.*;

// THIS CODE IS GENERATED BY greenDAO, EDIT ONLY INSIDE THE "KEEP"-SECTIONS

// KEEP INCLUDES - put your custom includes here
// KEEP INCLUDES END

/**
 * Entity mapped to table "ASSESSMENT".
 */
@Entity
public class Assessment {

    @Id(autoincrement = true)
    private Long id;
    private int assessment_id;
    private String letter_name;
    private String first_name;
    private String middle_name;
    private String last_name;
    private String first_icon;
    private String middle_icon;
    private String last_icon;

    // KEEP FIELDS - put your custom fields here
    // KEEP FIELDS END

    @Generated
    public Assessment() {
    }

    public Assessment(Long id) {
        this.id = id;
    }

    @Generated
    public Assessment(Long id, int assessment_id, String letter_name, String first_name, String middle_name, String last_name, String first_icon, String middle_icon, String last_icon) {
        this.id = id;
        this.assessment_id = assessment_id;
        this.letter_name = letter_name;
        this.first_name = first_name;
        this.middle_name = middle_name;
        this.last_name = last_name;
        this.first_icon = first_icon;
        this.middle_icon = middle_icon;
        this.last_icon = last_icon;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public int getAssessment_id() {
        return assessment_id;
    }

    public void setAssessment_id(int assessment_id) {
        this.assessment_id = assessment_id;
    }

    public String getLetter_name() {
        return letter_name;
    }

    public void setLetter_name(String letter_name) {
        this.letter_name = letter_name;
    }

    public String getFirst_name() {
        return first_name;
    }

    public void setFirst_name(String first_name) {
        this.first_name = first_name;
    }

    public String getMiddle_name() {
        return middle_name;
    }

    public void setMiddle_name(String middle_name) {
        this.middle_name = middle_name;
    }

    public String getLast_name() {
        return last_name;
    }

    public void setLast_name(String last_name) {
        this.last_name = last_name;
    }

    public String getFirst_icon() {
        return first_icon;
    }

    public void setFirst_icon(String first_icon) {
        this.first_icon = first_icon;
    }

    public String getMiddle_icon() {
        return middle_icon;
    }

    public void setMiddle_icon(String middle_icon) {
        this.middle_icon = middle_icon;
    }

    public String getLast_icon() {
        return last_icon;
    }

    public void setLast_icon(String last_icon) {
        this.last_icon = last_icon;
    }

    // KEEP METHODS - put your custom methods here
    // KEEP METHODS END

}
